sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t manish16399/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manish16399/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-873976861066"
  bucket_path: "docker"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master