sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t manish16399/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true manish16399/docker-react npm run test